import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "@next/font/google";
import Navbar from "@/components/ui/Navbar/Navbar";
// import { AnimatedNavbar } from "@/components/ui/AnimatedNavbar/AnimatedNavbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Rakesh Bansal - Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <link
          rel="icon"
          href="/favicon-16x16.png"
          sizes="16x16"
          type="image/png"
        />
        <link
          rel="icon"
          href="/favicon-32x32.png"
          sizes="32x32"
          type="image/png"
        />
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={`${poppins.variable} font-sans antialiased`}>
        <div className="relative w-full flex items-center justify-center">
          <Navbar />
        </div>
        {/* <div className="relative w-full flex items-center justify-center">
          <AnimatedNavbar className="top-0" />
        </div> */}
        {children}
      </body>
    </html>
  );
}
